### PR TITLE
Postgresql compatibility work

### PR DESCRIPTION
**Pull request by frconil**
These commits should ensure compatibility with postgresql schemas AND mysql schemas.

They have been tested with both mysql and postgresql with no issues found, but any additional testing is welcome.

### CODE REVIEW

**Comment by sammcj** [comment]
@miketanderson @mephux @jandre sorry to ping you directly but there's been no movement on this and I'm wondering if we could get this accepted upstream asap if you deem it acceptable.

We're wanting to roll out snorby but this is currently blocking us, hence why @frconil has contributed the fixes to the project.

Thanks,

**Comment by nunogt** [comment]
Hi, thanks for this work, postgresql support is a very welcome addition. 

I'm seeing a few issues with the rake snorby setup step if reusing an existing snort database with production data:

```
cd /opt/snorby
RAILS_ENV=production bundle exec rake snorby:setup
acc83d2cdfb69d14c09742c1912aecb4aec099a99e594831510e9a52f020ccf7db06266d1131731c09d62ed5a79645ce418b4eb7236f536a04fe08cbede83e4a
createdb: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
[datamapper] Finished auto_upgrade! for :default repository 'snort'
[~] Adding `id` to the event table
[~] fixing database types for ip addresses
rake aborted!
ERROR:  index "index_iphdr_ip_src" does not exist

Tasks: TOP => db:seed
``` 

If the database is empty, however, rake seems to complete without error.

**Comment by frconil** [comment]
Hi @nunogt , will look into it today, thanks for letting me know.

**Comment by frconil** [comment]
Okay, added some sanity checks for indices/data types with postgres. The db:create issue seems to be non critical (and possibly linked to the fact the recommended setup is to not run snorby as a root/superuser account in your db of choice)

**Comment by nunogt** [comment]
Great, I gave it another go and I'm not seeing the issue anymore:
```
$ docker logs -f snorby
10619c0156ee777c9ef07c6ffcfdfb9c863e097c59d2580e08f057102764d9532f808af5de16dd923e66fc881d77d94d093ea82acb6eb0cb1f8f3662588b23fd
createdb: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
[datamapper] Finished auto_upgrade! for :default repository 'snort'
[~] Adding `id` to the event table
[~] fixing database types for ip addresses
NOTICE:  index "index_iphdr_ip_src" does not exist, skipping
NOTICE:  index "index_iphdr_ip_dst" does not exist, skipping
[~] Building aggregated_events database view
[~] Building events_with_join database view
* Removing old jobs
* Starting the Snorby worker process.
* Adding jobs to the queue
=> Booting Thin
=> Rails 3.1.12 application starting in production on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
>> Thin web server (v1.5.1 codename Straight Razor)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:3000, CTRL+C to stop
```
Web interface works fine as far as I can tell. As for the privileged user, I'm running this inside a container so running as root is not a big deal. 

Thanks again for contributing back. Let's hope this gets merged soon.

**Comment by sammcj** [comment]
Any update on getting the merged? ping @snorby @jandre @acmarques @terracatta

**Comment by nunogt** [comment]
I'm seeing some issues with barnyard2 after the schema changes made by snorby:

```
barnyard2[42]: Barnyard2 spooler: Event cache size set to [2048] 

barnyard2[42]: Log directory = /var/log/snort

barnyard2[42]: INFO database: Defaulting Reconnect/Transaction Error limit to 10 

barnyard2[42]: INFO database: Defaulting Reconnect sleep time to 5 second 

barnyard2[42]: Initializing daemon mode

barnyard2[42]: Daemon parent exiting

barnyard2[43]: Daemon initialized, signaled parent pid: 42

barnyard2[43]: PID path stat checked out ok, PID path set to /var/run/

barnyard2[43]: Writing PID "43" to file "/var/run//barnyard2_eth0.pid"

barnyard2[43]: ERROR database: Query [SELECT vseq FROM schema] returned more than one result

barnyard2[43]: ERROR database: executing Select() with Query [SELECT vseq FROM schema] 

barnyard2[43]: FATAL ERROR: database problems with schema version, bailing...

barnyard2[43]: Barnyard2 exiting

barnyard2[43]: ERROR database: database: postgresql_error: ERROR:  integer out of range

barnyard2[43]: database: Closing connection to database "snort"
```

Snorby itself still works fine, but since barnyard refuses to start we're not getting any more alerts.

**Comment by frconil** [comment]
@nunogt I came across that bug and subsequently fixed it in https://github.com/frconil/snorby/commit/6f8c451632ef1ec7842461b61c102be777178a18 if you want to check it out.

It's the latest master of my fork.

**Comment by nunogt** [comment]
Hi @frconil thanks for the quick feedback. The bug occurred despite the inclusion of your latest patch. Is there a quick way to fix the db schema to something barnyard2 is happy to use again?

**Comment by frconil** [comment]
basically you would need to drop both views (aggregated and events_with_join) and rerun the setup task.

Let me know if this help :)

**Comment by hostingnuggets** [comment]
@snorby @jandre @acmarques @terracatta @nunogt any news when this PR will get integrated? nothing has happened since October 2015...

**Comment by nunogt** [comment]
Not sure if this project is still actively maintained, any takers for a fork?

**Comment by qha** [comment]
@nunogt Does your comment refer to this pull request or Snorby?

**Pull request merged**
